#!/bin/bash

function image_layers
{
  docker inspect -f '{{range .RootFS.Layers}}{{println .}}{{end}}' $1
}

for i in alpine:3.9 nginx:alpine mynginx mynginxcustom
do
  echo $i
  image_layers $i
done

